sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
      - name: facebook
        identifier: raw_gz_facebook
      - name: criteo
        identifier: raw_gz_criteo
      - name: bing
        identifier: raw_gz_bing
      - name: sale
        identifier: raw_gz_sales
        description: "Sales data with one row per product_id found in each orders_id."
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: date_date
            description: "Date of purchase"
            tests:
              - not_null
          - name: orders_id
            description: "Identifier of order"
            tests:
              - not_null
          - name: pdt_id
            description: "Product identifier"
          - name: revenue
            description: "Revenues"
          - name: quantity
            description: "The quantity of products purchased for a given order"
      - name: product
        identifier: raw_gz_product
        description: "Source table containing products data."
        columns:
          - name: products_id
            description: "Unique identifier for the product"
            tests:
              - not_null
          - name: purchase_price
            description: "Cost of goods"
          - name: revenue
            description: "Revenue generated from each sale"
      - name: ship
        identifier: raw_gz_ship
        description: "Source table containing shipping details."
        columns:
          - name: orders_id
            description: "Unique identifier for each order, linking to sales data"
            tests:
              - not_null
          - name: shipping_fee
            description: "Primary shipping fee for the order"
          - name: shipping_fee1
            description: "Additional shipping fee if applicable"
          - name: log_cost
            description: "Logistics cost for the order"
          - name: ship_cost
            description: "Total cost of shipping"
            tests:
              - not_null

models:
  - name: int_orders_margin
    description: "Margin calculation per order"
    columns:
      - name: orders_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null

  - name: int_sales_margin
    description: "Margin calculation per order line / product sales"
    columns:
      - name: orders_id
        description: "Orders key"
        tests:
          - not_null
      - name: products_id
        description: "Products key"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

  - name: int_orders_operational
    description: "Operational margin calculation per order"
    columns:
      - name: orders_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: operational_margin
        description: "Operational margin = margin + shipping_fee - logcost - ship_cost"
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: shipping_fee
        description: "The price the customer pays for shipping"
      - name: logcost
        description: "The cost of preparing the parcel in the distribution center/warehouse"
      - name: ship_cost
        description: "Shipping cost paid by Greenweez to the carrier/logistics provider"
