version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: "Date of launch"
          - name: paid_source
            description: "Amount paid"
          - name: campaign_key
            description: "Identifier key"
            tests:
              - not_null
          - name: campgn_name
            description: "Campaign name"
          - name: ad_cost
            description: "Cost of ads"
          - name: impression
            description: "Number of ad impressions"
          - name: click
            description: "Number of ad clicks"

      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: "Date of purchase"
            tests:
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: "Date of purchase"
            tests:
              - not_null

      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: "Date of purchase"
            tests:
              - not_null

      - name: sale
        identifier: raw_gz_sales
        description: "Sales data with one row per product_id found in each orders_id."
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: orders_id
            description: "Identifier of order"
            tests:
              - not_null
          - name: pdt_id
            description: "Product identifier"
          - name: revenue
            description: "Revenues from sales"
          - name: quantity
            description: "The quantity of products purchased for a given order"

      - name: product
        identifier: raw_gz_product
        description: "Source table containing products data."
        columns:
          - name: products_id
            description: "Unique identifier for the product"
            tests:
              - not_null
          - name: purchase_price
            description: "Cost of goods"
          - name: revenue
            description: "Revenue generated from each sale"

      - name: ship
        identifier: raw_gz_ship
        description: "Source table containing shipping details."
        columns:
          - name: orders_id
            description: "Unique identifier for each order, linking to sales data"
            tests:
              - not_null
          - name: shipping_fee
            description: "Primary shipping fee for the order"
          - name: shipping_fee1
            description: "Additional shipping fee if applicable"
          - name: log_cost
            description: "Logistics cost for the order"
          - name: ship_cost
            description: "Total cost of shipping"
            tests:
              - not_null

models:
  - name: int_orders_margin
    description: "Margin calculation per order"
    columns:
      - name: orders_id
        description: "Primary key for the order"
        tests:
          - unique
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null

  - name: int_sales_margin
    description: "Margin calculation per order line / product sales"
    columns:
      - name: orders_id
        description: "Order ID"
        tests:
          - not_null
      - name: products_id
        description: "Product ID"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Revenue generated per product"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products in the order"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

  - name: int_orders_operational
    description: "Operational margin calculation per order"
    columns:
      - name: orders_id
        description: "Primary key for the order"
        tests:
          - unique
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: operational_margin
        description: "Operational margin = margin + shipping_fee - logcost - ship_cost"
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase cost = quantity * purchase_price"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: shipping_fee
        description: "The price the customer pays for shipping"
      - name: logcost
        description: "Logistics cost incurred for order processing"
      - name: ship_cost
        description: "Shipping cost paid by the company to the carrier/logistics provider"

  - name: finance_days
    description: "View combining financial data with campaign metrics"
    columns:
      - name: date_date
        description: "Date of the record"
        tests:
          - not_null
      - name: ads_margin
        description: "Difference between operational margin and advertising costs"
       
      - name: average_basket
        description: "Average basket size for orders"
        tests:
          - not_null
      - name: operational_margin
        description: "Calculated as revenue minus all operational costs"
        
      - name: ads_cost
        description: "Total cost associated with advertising on this date"
        
      - name: ads_impression
        description: "Number of ad impressions shown on this date"
          
      - name: ads_clicks
        description: "Number of ad clicks on this date"
        
      - name: quantity
        description: "Total quantity of items sold"
        tests:
          - not_null
      - name: revenue
        description: "Total revenue generated on this date"
        tests:
          - not_null
      - name: purchase_cost
        description: "Cost of goods sold on this date"
        tests:
          - not_null
      - name: margin
        description: "Margin calculated as revenue minus purchase cost"
        tests:
          - not_null
      - name: shipping_fee
        description: "The shipping fee charged to customers"
        tests:
          - not_null
      - name: logcost
        description: "Logistics cost incurred for this date"
        tests:
          - not_null
      - name: ship_cost
        description: "Total cost of shipping incurred for this date"
        tests:
          - not_null
